import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HeaderActions } from "@/components/HeaderActions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
        suppressHydrationWarning
      >
        {/* Full-viewport gradient — covers header and all pages */}
        <div aria-hidden="true" className="pointer-events-none fixed inset-0 -z-10 overflow-hidden">
          <div className="absolute -top-44 left-1/2 h-[540px] w-[540px] -translate-x-1/2 rounded-full bg-fuchsia-500/20 blur-3xl" />
          <div className="absolute -bottom-52 right-10 h-[540px] w-[540px] rounded-full bg-sky-500/15 blur-3xl" />
        </div>

        <header className="flex items-center justify-between px-6 py-4">
          <Link
            href="/"
            className="inline-flex items-center gap-3 rounded-full bg-gradient-to-r from-violet-500/15 to-sky-500/10 px-4 py-2 backdrop-blur-md ring-1 ring-white/10 shadow-lg shadow-black/30 hover:from-violet-500/20 hover:to-sky-500/15"
          >
            <span className="relative inline-flex h-9 w-9 items-center justify-center overflow-hidden rounded-xl bg-gradient-to-br from-sky-400 via-cyan-400 to-fuchsia-500 text-white shadow-sm ring-1 ring-white/20">
              <svg viewBox="0 0 24 24" fill="none" className="h-5 w-5" aria-hidden="true">
                <path d="M9 18 3 12l6-6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                <path d="M15 6l6 6-6 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            </span>
            <div className="leading-tight">
              <div className="text-3xl font-semibold text-white">
                <span className="text-sky-400">C</span>oda
              </div>
            </div>
          </Link>

          <div className="flex items-center gap-2">
            <HeaderActions />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
